### ISSUE TITLE
Longer youtube videos can cause hanging

### ISSUE THREAD

**Issue by HeteroChromia420** [SuperrSonic/WiiMC-SSLC#20]
Title. longer (around 1 hour length or longer) youtube videos on riitube are prone to Hang wiiMC.

**Comment by SuperrSonic** [comment]
WiiMC has always had a bug where if the connection isn't active for a certain amount of time it will disconnect and quit the video. Since back then many users wanted WiiMC for streaming video I enabled seeking, eventually I found that if I seek once a disconnect occurs and mark the end-of-file as false, I can save the connection somewhat.

Since this yt thing downloads the video from the start and streams it as it downloads, seeking doesn't work and hangs because eof never happens.

I don't think I can fix this, but I can add an exception for riitube links so if a disconnect occurs it will gracefully end the video.
Or remove the hack altogether since it barely works.

**Comment by HeteroChromia420** [comment]
is there a possible way to minimize this problem? like occasionally pinging/checking for a heartbeat just for the sake of keeping the connection busy with something. this sounds like a bit of a hack, but that's the best idea i had while thinking about it.

**Comment by SuperrSonic** [comment]
Hanging should be fixed.

**Comment by HeteroChromia420** [comment]
Seems that it's still a problem, as of SSLC 3.0.0, long (1 hour and above) youtube videos still cause wiiMC to hang after playing for ~30-40 minutes(?), so it does seem that this issue isn't fixed yet

**Comment by SuperrSonic** [comment]
I'll give this a check again soon.

**Comment by HeteroChromia420** [comment]
i'd love to be more useful somehow, is there a way i can somehow generate a log file? as i can do it consistently.

**Comment by SuperrSonic** [comment]
There's no logging exposed to the WiiMC side. I tested video zvBrxuJazo0 using the riitube link about 5 times in the last few days, it always failed and never showed more than some 20 minutes, but no hanging so I can't replicate it.

The only thing that stands out to me is that http streaming isn't this unreliable when using other hosts, and that on Dolphin the riitube link manages to play all the way.

When it hangs are you able to eventually exit out of the app by turning off the wiimote? Are you able to trigger the hang by loading into a video, pausing it for at least a minute and then letting it play? It should then fail after a few minutes or less and return you to the WiiMC menu.

**Comment by HeteroChromia420** [comment]
> There's no logging exposed to the WiiMC side. I tested video zvBrxuJazo0 using the riitube link about 5 times in the last few days, it always failed and never showed more than some 20 minutes, but no hanging so I can't replicate it.
> 
> The only thing that stands out to me is that http streaming isn't this unreliable when using other hosts, and that on Dolphin the riitube link manages to play all the way.
> 
> When it hangs are you able to eventually exit out of the app by turning off the wiimote? Are you able to trigger the hang by loading into a video, pausing it for at least a minute and then letting it play? It should then fail after a few minutes or less and return you to the WiiMC menu.

i've tested video DSFKMGuE2r4 which is just barely over an hour. i managed to play around 38 minutes before the wii hangs, no inputs seem to work while the wii is in this state.

The wii does eventually recover from the hang, but closes out of the video.

**Comment by HeteroChromia420** [comment]
with enhanced resolution on, when it hangs, it stays at a black screen. Just a interesting tidbit i found out while playing around with the settings.

**Comment by SuperrSonic** [comment]
When enhanced resolution is running, the menu can't use it due to stability issues, so it changes back to normal rendering which shows a few distorted frames during the change, the only way I know to avoid this is to blackout the screen, which I do for several frames to avoid flicker. Since this feature is adapted from mplayer ce, there's not much documentation, so reverting it gracefully is pretty much unknown, other than a few Virtual Console Arcade games doing it for the home menu, I assume because Dolphin's 'Immediately present XFB' setting doesn't cause the slices to go out of order.

...Anyway, since this issue seems to be close to the "holy grail" of reconnecting video streams, I don't want to do it, the amount of testing and time wasted is too high, sorry. I may consider a 'download to device' option, which would at least fix seeking in yt videos. I've also taken out the bad reconnection hack in the latest commits as a last resort.
